# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: devel
sudo: FALSE
compiler: clang

cache:
  apt: true
  packages: true
  ccache: true

warnings_are_errors: TRUE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

before_script:
  - R -e "install.packages('StanHeaders', type = 'source')"
  - R -e "install.packages('rstan', type = 'source')"
  
addons:
  apt:
    packages:
      - jags
r_binary_packages:
   - rstanarm
   - Matrix
   - coda
   - testthat
   - rmarkdown
   - knitr
   - stringr
   - mvtnorm

